baseURL = "/"
title = "Indonesian AI Research"
theme = "hugo-geekdoc"

staticDir = ['static']

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[params]
  geekdocLogo = "images/flag.png"
  geekdocSearchShowParent = true
  geekdocBreadcrumb = false
  geekdocCollapseAllSections = true